### ISSUE TITLE
Running HaploGrep v2.1.18on MacOS

### ISSUE THREAD

**Issue by elffuos** [seppinho/haplogrep-cmd#21]
Hi, I got the following error. Please help me. best regards, John Goh

Welcome to HaploGrep v2.1.18
(c) Division of Genetic Epidemiology, Medical University of Innsbruck
Hansi Weissensteiner, Lukas Forer, Dominic Pacher and Sebastian Schoenherr

phylotree/phylotree17.xml
Parameters:
Input Format: fasta
Phylotree Version: 17
Reference: rCRS
Extended Report: false
Used Metric: kulczynski
Chip array data: false
Lineage: false

Start Classification...
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/gv/9nbhl4qn1nqdjm4vv84txy980000gn/T/jbwa-0.7.17/libbwajni.so: dlopen(/private/var/folders/gv/9nbhl4qn1nqdjm4vv84txy980000gn/T/jbwa-0.7.17/libbwajni.so, 1): no suitable image found.  Did find:
	/private/var/folders/gv/9nbhl4qn1nqdjm4vv84txy980000gn/T/jbwa-0.7.17/libbwajni.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/private/var/folders/gv/9nbhl4qn1nqdjm4vv84txy980000gn/T/jbwa-0.7.17/libbwajni.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at importer.FastaImporter.load(FastaImporter.java:59)
	at genepi.haplogrep.main.Haplogrep.run(Haplogrep.java:151)
	at genepi.base.Tool.start(Tool.java:193)
	at genepi.haplogrep.main.Haplogrep.main(Haplogrep.java:197)

**Comment by seppinho** [comment]
see #18
