### ISSUE TITLE
Bug on running haplogrep on windows

### ISSUE THREAD

**Issue by elffuos** [seppinho/haplogrep-cmd#24]
Start Classification...
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Desktop\mtDNA\jbwa-0.7.17\libbwajni.so: %1 is not a valid Win32 application
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at importer.FastaImporter.load(FastaImporter.java:65)
        at genepi.haplogrep.main.Haplogrep.run(Haplogrep.java:151)
        at genepi.base.Tool.start(Tool.java:193)
        at genepi.haplogrep.main.Haplogrep.main(Haplogrep.java:197)

**Comment by seppinho** [comment]
Not sure if there is a windows library for jbwa. Currently alignment only works in Unix and MacOS.
See here: https://github.com/lindenb/jbwa/pull/5

**Comment by seppinho** [comment]
closing this issue for now. fasta currently only supported for linux and mac.
