### ISSUE TITLE
--rsrs option crashes

### ISSUE THREAD

**Issue by JoshuaDanielRubin** [seppinho/haplogrep-cmd#49]
I would like to use HaploGrep to classify a FASTA sample with respect to the RSRS, but the option does not seem to work. I get the error:

`[classify, --in, simulations/Q1.fa, --out, here, --format, fasta, --rsrs]
phylotree17_FU1_rsrs.xml
Parameters:
Input format: fasta
Phylotree version: 17_FU1
Reference: RSRS
Extended report: false
Skip alignment rules: false
Used metric: kulczynski
Chip array data: false
Lineage: 0

Start Classification...
[M::bwa_idx_load_from_disk] read 0 ALT contigs
java.io.FileNotFoundException: phylotree17_FU1_rsrs.xml (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
        at phylotree.PhylotreeManager.getPhylotree(PhylotreeManager.java:53)
        at genepi.haplogrep.util.HgClassifier.run(HgClassifier.java:25)
        at genepi.commands.HaplogrepCommand.call(HaplogrepCommand.java:178)
        at genepi.commands.HaplogrepCommand.call(HaplogrepCommand.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at genepi.App.main(App.java:59)
java.net.MalformedURLException
        at java.base/java.net.URL.<init>(URL.java:702)
        at java.base/java.net.URL.<init>(URL.java:564)
        at java.base/java.net.URL.<init>(URL.java:511)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:649)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:489)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:807)
        at phylotree.Phylotree.<init>(Phylotree.java:60)
        at phylotree.PhylotreeManager.getPhylotree(PhylotreeManager.java:60)
        at genepi.haplogrep.util.HgClassifier.run(HgClassifier.java:25)
        at genepi.commands.HaplogrepCommand.call(HaplogrepCommand.java:178)
        at genepi.commands.HaplogrepCommand.call(HaplogrepCommand.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at genepi.App.main(App.java:59)
Caused by: java.lang.NullPointerException
        at java.base/java.net.URL.<init>(URL.java:608)
        ... 24 more
`

However the program works without the --rsrs flag.

**Comment by haansi** [comment]
Sorry for the delay, was offline the last days. If you want to use the rsrs - then you need to specify the former tree phylotree17 - as the latest tree by Duer et al is provided for rCRS only. 

the parameter to add   --phylotree 17

**Comment by JoshuaDanielRubin** [comment]
Ah, I see. Thanks!

**Comment by N-atalia** [comment]
> Sorry for the delay, was offline the last days. If you want to use the rsrs - then you need to specify the former tree phylotree17 - as the latest tree by Duer et al is provided for rCRS only.
> 
> the parameter to add --phylotree 17

Hi! is this still the case? 
cheers

**Comment by seppinho** [comment]
yes
